title: Jekyll MAC renderer
email: ivancea96@outlook.com
description: A MAC JSON renderer in Jekyll for GitHub Pages
url: "https://github.com/ivancea/jekyll-mac-renderer"
repository: ivancea/jekyll-mac-renderer
twitter_username: ivancea96
github_username:  ivancea
github:
  is_project_page: false

data_dir: CV