name: "Deploy MAC CV to GitHub Pages"
description: "Deploys a MAC CV repository to GitHub Pages"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Check that the repository is correct
      shell: bash
      run: |
        if [ ! -f CV/MAC.json ]; then
          echo "CV/MAC.json does not exist"
          exit 1
        fi
    - name: Copy MAC to action directory
      shell: bash
      run: |
        rsync --recursive --ignore-existing CV ${{ github.action_path }}/
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build package
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm ci
        npm run build
    - name: Generate HTML
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        mkdir page
        npx . CV/MAC.json > page/index.html
    - name: Create .nojekyll file
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        touch ./page/.nojekyll
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ github.action_path }}/page
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
