name: "Deploy MAC CV to GitHub Pages"
description: "Deploys a MAC CV repository to GitHub Pages"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Check that the repository is correct
      shell: bash
      run: |
        if [ ! -f CV/MAC.json ]; then
          echo "CV/MAC.json does not exist"
          exit 1
        fi
    - name: Copy MAC to action directory
      shell: bash
      run: |
        rsync --recursive --ignore-existing CV ${{ github.action_path }}/
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm run build
      working-directory: ${{ github.action_path }}
    - run: npx mac-renderer CV/MAC.json > page/index.html
      working-directory: ${{ github.action_path }}
    - name: Create .nojekyll file
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        touch ./page/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.action_path }}/page
