name: "Deploy MAC CV to GitHub Pages"
description: "Deploys a MAC CV repository to GitHub Pages"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Debug
      shell: bash
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        echo "Action directory: ${{ github.action_path }}"
        ls -la ${{ github.action_path }}
    - name: Copy Jekyll action files
      shell: bash
      run: |
        cp -rn ${{ github.action_path }} ./
    - name: Check that the repository is correct
      shell: bash
      run: |
        if [ ! -f CV/MAC.json ]; then
          echo "CV/MAC.json does not exist"
          exit 1
        fi
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: helaili/jekyll-action@2.4.0
      with:
        token: ${{ inputs.github-token }}
